<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="c3PO" name="Command line test" tests="7" failures="1" timestamp="17 Nov 2015 19:29:37 GMT" time="2.781" errors="0">
  <testcase name="createNullNameTest" time="0.095" classname="cz.fi.muni.pz165.tests.CustomerTest">
    <failure type="org.testng.TestException" message="
Expected exception javax.persistence.PersistenceException but got org.testng.TestException: 
Expected exception javax.persistence.PersistenceException but got javax.validation.ConstraintViolationException: Validation failed for classes [cz.fi.muni.pa165.dogbarber.entity.Customer] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage=&amp;apos;may not be null&amp;apos;, propertyPath=name, rootBeanClass=class cz.fi.muni.pa165.dogbarber.entity.Customer, messageTemplate=&amp;apos;{javax.validation.constraints.NotNull.message}&amp;apos;}
]">
      <![CDATA[org.testng.TestException: 
Expected exception javax.persistence.PersistenceException but got javax.validation.ConstraintViolationException: Validation failed for classes [cz.fi.muni.pa165.dogbarber.entity.Customer] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='may not be null', propertyPath=name, rootBeanClass=class cz.fi.muni.pa165.dogbarber.entity.Customer, messageTemplate='{javax.validation.constraints.NotNull.message}'}
]
Expected exception javax.persistence.PersistenceException but got javax.validation.ConstraintViolationException: Validation failed for classes [cz.fi.muni.pa165.dogbarber.entity.Customer] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='may not be null', propertyPath=name, rootBeanClass=class cz.fi.muni.pa165.dogbarber.entity.Customer, messageTemplate='{javax.validation.constraints.NotNull.message}'}
]
	... 25 more
Caused by: javax.validation.ConstraintViolationException: Validation failed for classes [cz.fi.muni.pa165.dogbarber.entity.Customer] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='may not be null', propertyPath=name, rootBeanClass=class cz.fi.muni.pa165.dogbarber.entity.Customer, messageTemplate='{javax.validation.constraints.NotNull.message}'}
]
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:160)
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:95)
	at org.hibernate.action.internal.EntityIdentityInsertAction.preInsert(EntityIdentityInsertAction.java:214)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:92)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:490)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:195)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:179)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:214)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:324)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:288)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:194)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125)
	at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:84)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:206)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:149)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:75)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:811)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:784)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:789)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1181)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:289)
	at com.sun.proxy.$Proxy39.persist(Unknown Source)
	at cz.fi.muni.pa165.dogbarber.dao.CustomerDaoImpl.createCustomer(CustomerDaoImpl.java:34)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy41.createCustomer(Unknown Source)
	at cz.fi.muni.pz165.tests.CustomerTest.createNullNameTest(CustomerTest.java:83)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:172)
	... 27 more
... Removed 53 stack frames]]>
    </failure>
  </testcase> <!-- createNullNameTest -->
  <testcase name="createNullTest" time="0.0" classname="cz.fi.muni.pz165.tests.CustomerTest"/>
  <testcase name="createSuccessTest" time="0.029" classname="cz.fi.muni.pz165.tests.CustomerTest"/>
  <testcase name="deleteNullTest" time="0.0" classname="cz.fi.muni.pz165.tests.CustomerTest"/>
  <testcase name="deleteTest" time="0.13" classname="cz.fi.muni.pz165.tests.CustomerTest"/>
  <testcase name="findAllTest" time="0.003" classname="cz.fi.muni.pz165.tests.CustomerTest"/>
  <testcase name="updateTest" time="0.005" classname="cz.fi.muni.pz165.tests.CustomerTest"/>
</testsuite> <!-- Command line test -->
